# Generated by Django 5.1.2 on 2025-01-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swastik', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getintouch',
            name='address',
        ),
        migrations.RemoveField(
            model_name='getintouch',
            name='company',
        ),
        migrations.RemoveField(
            model_name='getintouch',
            name='phone',
        ),
    ]
